# Generated by Django 6.0.3 on 2026-04-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='temp', max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-04-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='price',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='slug',
            field=models.SlugField(default='temp', max_length=220, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
