# Generated by Django 6.0.3 on 2026-04-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_description_category_slug_design_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentattribute',
            name='title',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
    ]
