# Generated by Django 6.0.3 on 2026-04-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_design_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Enter a discount percentage from 0 to 100. Leave as 0 for no discount.'),
        ),
    ]
